# group_vars/project.ansibled.yml
# ---
# specify VPC details and AWS credentials

# general details about our VPC
vpc_name: ansibled-vpc
vpc_key: ansibled-key
vpc_dns_zone: ansibled
vpc_use_nat: false

# credentials for AWS (no, they aren't real...)

# Logentries REST API key -- read/write
