# group_vars/project.ansibled.yml
# ---
# specify VPC details and AWS credentials

# general details about our VPC
vpc_name: ansibled-vpc
vpc_key: ansibled-key
vpc_dns_zone: ansibled
vpc_use_nat: false

# credentials for AWS (no, they aren't real...)
aws_region: "{{ lookup('env','AWS_REGION') }}"
aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
aws_secret_key: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"

# Logentries REST API key -- read/write
