# vpc.yml
# ---
# playbook that runs our VPC tasks for any hosts in the `vpc` group, providing AWS credentials in the environment 

- hosts: vpc
  environment:
    DERP: "LOL"
  tasks:

    - include_tasks: tasks/vpc/setup.vpc.yml
    - include_tasks: tasks/vpc/setup.gateways.yml
    - include_tasks: tasks/vpc/facts.yml
